# Generated by Django 2.2.24 on 2021-07-15 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ToDoItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("toDoName", models.CharField(max_length=256)),
                ("toDoDate", models.DateTimeField()),
                ("toDoDescription", models.TextField()),
            ],
        ),
    ]
